banzaicloud/koperator-docs

docs/_index.md, docs/install-kafka-operator.md, docs/monitoring.md, docs/scenarios.md, docs/ssl.md, docs/test.md
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
=> Closes links to avoid redirects

docs/_index.md
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | none
Updates Kafka operator comparison table -- Strimzi supports rolling updates as well as cluster scaling with Cruise Control. 
I was asked to update PR for updating it on #kafka-operator slack channel. 
None
=> docs: update operator comparison strimzi points

docs/_index.md
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
=> Remove outdated product comparison table

docs/ssl.md
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
=> Adds a note and link about ACL handling inSupertubes

docs/benchmarks/_index.md
=> Updates a link to the new try.pipeline.banzai.cloud url

docs/developer.md, docs/features.md, docs/install-kafka-operator.md, docs/monitoring.md, docs/scenarios.md
=> Removes obsolete shortcode, will be replaced centrally

docs/delete-kafka-operator.md, docs/install-kafka-operator.md
Based on https://community-banzaicloud.slack.com/archives/CK75ATB29/p1598942506005400?thread_ts=1598849183.004300&cid=CK75ATB29
=> Documents how to delete the kafka operator

docs/support.md
=> Typo correction

docs/install-kafka-operator.md
| Bug fix?        | yes
| Related tickets | 
Without that the install breaks with:
```
Error: create: failed to create: namespaces "zookeeper" not found
```
=> add --create-namespace to zookeeper helm command

docs/install-kafka-operator.md
| Bug fix?        | yes
| Related tickets | 
It was missing.
=> add cert-manager CRD install

docs/create-topic.sample, docs/create-zookeeper.sample, docs/install-kafka-operator.md, docs/test.md
=> Install kafka-operator corrections and updates

docs/install-kafka-operator.md
=> Single-source supertubes install command

docs/_index.md, docs/benchmarks/_index.md
=> Update pipeline references

docs/troubleshooting/common-errors.md, docs/upgrade-kafka-operator.md
Sorry, I've merged the previous PR without committing the corrections
=> Troubleshooting corrections from Balint's review

docs/create-kafkauser.sample, docs/enable-ssl.sample, docs/external-listener/index.md, docs/headless/index.md, docs/headless/warning-listener-protocol.md, docs/install-kafka-operator.md, docs/kafkacat-ssl.sample, docs/ssl.md, docs/test.md
Updates using Kafka with SSL (no acl)
Requires https://github.com/banzaicloud/kafka-operator/pull/568
=> Ssl internal noacl

docs/external-listener/index.md
=> Adds sasl_plaintext to external listener docs

docs/external-listener/index.md
=> Adds missing element to advertised listener name

docs/compatibility-matrix.md
=> Adds supported versions and compatibility matrix

docs/monitoring.md
=> Doc updates for https://github.com/banzaicloud/kafka-operator/issues/398

docs/benchmarks/_index.md, docs/create-topic.sample, docs/test.md, docs/topics.md
=> Formatting corrections

docs/compatibility-matrix.md, docs/install-kafka-operator.md
=> Updates cert-manager version numbers

docs/create-zookeeper.sample
Update zk example config to align with the results on the table listed below this command
=> Update zk example config to align with the results

docs/compatibility-matrix.md
=> Compatibility matrix update for 0.20.0

docs/ssl.md
=> Review corrections

docs/tips-tricks.md
=> Fix Kafka operator strings that sneaked back from old PR

docs/kafkacat-ssl.sample, docs/test.md
=> Replace kafkacat with kcat

docs/external-listener/index.md
| New feature?    |yes
Update istioingress  config howto for external listener due to istio operator v2
=> Update istioingress  config howto for external listeners due to istio operator v2

docs/compatibility-matrix.md, docs/install-kafka-operator.md
Version bumps for koperator 0.21.1
Prepare release 0.21.1
=> Version bumps for koperator 0.21.1

docs/compatibility-matrix.md, docs/install-kafka-operator.md
Added koperator v0.21.2 to docs
Prepare koperator v0.21.2 patch release
=> Version bumps for koperator 0.21.2

docs/test.md
=> Update kafka image versions in sample commands

docs/tips-tricks.md
https://github.com/banzaicloud/koperator/pull/824
=> Tips-Tricks - retrieving broker configuration when downscale running

docs/pre-provisioned-volumes.md
=> Review and formatting corrections

docs/compatibility-matrix.md
=> Koperator 0.22 compatibility matrix

docs/install-kafka-operator.md
Update kubectl command to use the latest CRD that was introduced in Koperator v0.22.0
Users might run into problems while installing Koperator with the missing CRD
=> Update kubectl command to use version 0.22.0 koperator CRDs

docs/_index.md
Fix broken link in this page https://smm-docs.eticloud.io/sdm/koperator/
=> Fix koperator architecture image link

docs/benchmarks/_index.md, docs/install-kafka-operator.md
Update steps in "Benchmarking Kafka" page under calisti.app: https://docs.calisti.app/sdm/koperator/benchmarks/
Steps are outdated
The steps would require changes in https://github.com/banzaicloud/koperator/pull/927 to work
=> Update Benchmarking Kafka docs

docs/install-kafka-operator.md
=> Include adding openshift permissions in the install steps

docs/external-listener/index.md
=> Fix misspelled parameter `advertized.listeners`

docs/benchmarks/_index.md, docs/install-kafka-operator.md
cherry-pick a028f85016bbe74344df16810f2a568b2973c041 into the master branch
The steps are outdated
=> Update Benchmarking Kafka docs (#87)

docs/rackawareness/index.md
=> Rack awareness fix

docs/install-kafka-operator.md
=> Style and formatting fixes

docs/create-zookeeper.sample, docs/external-listener/index.md, docs/install-kafka-operator.md, docs/test.md
| New feature?    | yes
Add openshift installation docs
=> Add openshift installation docs

docs/external-listener/index.md
| Q               | A |
| --------------- | --- |
| Bug fix?        | no |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |
Add doc about node IP for advertise.listeners
=> Add node IP for advertised.listeners

docs/_index.md
| New feature?    | yes
| Related tickets | -
Updated the current version to 0.24.0.
That's the latest release now.
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~
- ~Related Helm chart(s) updated (if needed)~
=> Updated current version to 0.24.0

docs/install-kafka-operator.md
=> Fix broken anchor

docs/create-zookeeper.sample, docs/install-kafka-operator.md, docs/test.md
Update some commands to use a more precise version
To make the docs look nicer and cleaner
=> Update commands and wordings

docs/install-kafka-operator.md
| Bug fix?        | yes
| Related tickets | -
Fixed \ at new line in Koperator Helm install step.
Because the command executes improperly otherwise.
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~
- ~Related Helm chart(s) updated (if needed)~
=> Fixed \ at new line in Koperator Helm install step

docs/compatibility-matrix.md
Please check the version numbers
=> Updates compatibility matrix

docs/_index.md
| Related tickets | -
Bumped the Koperator version to 0.24.1
To use the latest released version in the docs as reference.
https://github.com/banzaicloud/koperator/releases/tag/v0.24.1
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~
- ~Related Helm chart(s) updated (if needed)~
=> Bumped the Koperator version to 0.24.1

docs/install-kafka-operator.md
=> Removes username from sample output

docs/ssl.md
To resolve this: https://github.com/banzaicloud/koperator-docs/pull/116#discussion_r1193598148
=> Fit minor grammar

docs/configurations/_index.md, docs/configurations/kafkacluster-cr/_index.md, docs/configurations/kafkacluster-cr/examples/_index.md, docs/delete-kafka-operator.md, docs/enable-ssl.sample, docs/install-kafka-operator.md, docs/scenarios.md, docs/support.md, docs/troubleshooting/_index.md
Ports changes that were missing from the master branch
=> Sdm to master sync 2023 05 17

docs/_index.md, docs/scenarios.md
=> Fix htmlcheck errors
